package project.gui.admin;

import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;

public class ManageAcademicLeaders extends FrameFormat {

    private Admin sessionUser;
    private DefaultTableModel model = new DefaultTableModel(
        new String[]{"Leader ID", "Name", "Email", "Lecturers Assigned", "Modules Assigned"}, 0
    );
    
    public ManageAcademicLeaders(Admin sessionUser) {
        initComponents();
        this.sessionUser = sessionUser;
        for(Leader x : InteractTxt.allLeader){
            model.addRow(new String[]{x.getId(), x.getName(), x.getEmail(), x.getLecturersAsString(), x.getModulesAsString()});
        }
        
        Tools.enableTooltip(LeaderTable, Set.of(2, 3, 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LeaderTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Academic Leaders");

        LeaderTable.setModel(model);
        LeaderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeaderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LeaderTable);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        openPage(new Dashboard(sessionUser));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField nameField = new JTextField(25);
        JTextField emailField = new JTextField(25);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);

        while(true){
            int result = JOptionPane.showConfirmDialog(this, panel, "New Academic Leader", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result != JOptionPane.OK_OPTION) break;
            
            if (result == JOptionPane.OK_OPTION) {
                String name = nameField.getText().trim();
                String email = emailField.getText().trim();
                
                ValidationResult nameResult = ErrorChecking.checkInput(name);
                ValidationResult emailResult = ErrorChecking.checkEmail(email);
                
                if (nameResult != ValidationResult.OK) {
                    showNameError(nameResult);
                }else if (emailResult != ValidationResult.OK) {
                    showEmailError(emailResult);
                }else{
                    int max = 0;
                    for(Lecturer x : InteractTxt.allLecturer){
                        String numPart = x.getId().substring(2);
                        int num = Integer.parseInt(numPart);
                        if (num > max) {
                            max = num;
                        }
                    }
                    for(Leader x : InteractTxt.allLeader){
                        String numPart = x.getId().substring(2);
                        int num = Integer.parseInt(numPart);
                        if (num > max) {
                            max = num;
                        }
                    }
                    String id = "lc" + (max + 1);

                    String password = Tools.GeneratePW();

                    String [] userdata = {id, name, email, password, "leader"};
                    InteractTxt.allLeader.add(new Leader(userdata));

                    InteractTxt.writeUser();
                    Leader New = InteractTxt.checkLeaID(id);
                    model.addRow(new String[]{New.getId(), New.getName(), New.getEmail()});
                    break;
                }
            }
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void LeaderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderTableMouseClicked
        int row = LeaderTable.getSelectedRow();
        Leader Lea = InteractTxt.allLeader.get(row);

        JTextField nameField = new JTextField(25);
        nameField.setText(Lea.getName());
        JTextField emailField = new JTextField(25);
        emailField.setText(Lea.getEmail());

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);

        while(true){
            Object[] options = {"OK", "Delete", "Cancel"};
            int result = JOptionPane.showOptionDialog(this,panel,Lea.getId(),JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[2]);
            if (result != 0 && result != 1) break;
            
            if (result == 0) {
                String name = nameField.getText().trim();
                String email = emailField.getText().trim();
                
                ValidationResult nameResult = ErrorChecking.checkInput(name);
                ValidationResult emailResult = ErrorChecking.checkEmail(email);
                
                if (nameResult != ValidationResult.OK) {
                    showNameError(nameResult);
                }else if (emailResult != ValidationResult.OK && !email.equals(Lea.getEmail())) {
                    showEmailError(emailResult);
                }else{
                    Lea.setName(name);
                    Lea.setEmail(email);

                    InteractTxt.writeUser();

                    model.setValueAt(name, row, 1);
                    model.setValueAt(email, row, 2);
                    break;
                }
            }
            
            if (result == 1) {
                if(Lea.leaderTeam.isEmpty() && Lea.Lea_Modules.isEmpty()){
                    int confirm = JOptionPane.showConfirmDialog(this, "Do you sure to delete the Leader?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.OK_OPTION) {
                        InteractTxt.allLeader.remove(Lea);

                        InteractTxt.saveDatabase();
                        model.removeRow(row);
                        break;
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Cannot Delete", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_LeaderTableMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageAcademicLeaders().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LeaderTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
