package project.gui.admin;

import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;

public class ManageClasses extends FrameFormat {

    private Admin sessionUser;
    private DefaultTableModel model = new DefaultTableModel(
        new String[]{"Class ID", "Name", "Class's Lecturer", "Intake Module", "Class's Students"}, 0
    );
    
    public ManageClasses(Admin sessionUser) {
        initComponents();
        this.sessionUser = sessionUser;
        for(project.roles.Class x : InteractTxt.allClass){
            model.addRow(new String[]{x.getClassId(), x.getClassName(), x.getLecId(), x.getIMID(), x.getStudentsAsString()});
        }
        
        Tools.enableTooltip(ClassTable, Set.of(4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClassTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Classes");

        ClassTable.setModel(model);
        ClassTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ClassTable);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        openPage(new Dashboard(sessionUser));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClassTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassTableMouseClicked
        int row = ClassTable.getSelectedRow();
        project.roles.Class Cla = InteractTxt.allClass.get(row);

        JTextField nameField = new JTextField(25);
        nameField.setText(Cla.getClassName());

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);

        while(true){
            Object[] options = {"OK", "Delete", "Cancel"};
            int result = JOptionPane.showOptionDialog(this,panel,Cla.getClassId(),JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[2]);
            if (result != 0 && result != 1) break;

            if (result == 0) {
                String name = nameField.getText().trim();

                if(ErrorChecking.checkInput(name).equals("null")){
                    JOptionPane.showMessageDialog(this, "Name is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("number")){
                    JOptionPane.showMessageDialog(this, "Name cannot in number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("String")){

                    Cla.setClassName(name);

                    InteractTxt.saveDatabase();

                    model.setValueAt(name, row, 1);
                    break;
                }
            }

            if (result == 1) {
                boolean delete = true;
                if (InteractTxt.checkIMID(Cla.getIMID()).IM_Classes.size() <= 1) {
                    delete = false;
                } else {
                    outer:
                    for(Student y : Cla.Class_Students){
                        for(StudentScore z : y.Stu_Scores){
                            if(InteractTxt.checkIMID(Cla.getIMID()).IM_Assessments.contains(z.getAssessment())){
                                delete = false;
                                break outer;
                            }
                        }
                    }
                }
                
                if(delete){
                    int confirm = JOptionPane.showConfirmDialog(this, "Do you sure to delete the Class?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.OK_OPTION) {
                        InteractTxt.allClass.remove(Cla);
                        if(!Cla.getLecId().equals("NA")){
                            InteractTxt.checkLecID(Cla.getLecId()).Lec_Classes.remove(Cla);
                        }
                        InteractTxt.checkIMID(Cla.getIMID()).IM_Classes.remove(Cla);
                        for(Student x : Cla.Class_Students){
                            x.Stu_Classes.remove(Cla);
                            x.GradesAndComments.removeIf(gc -> gc.getStuClass() == Cla);
                            
                        }
                        Cla.Class_Students.clear();

                        InteractTxt.saveDatabase();
                        model.removeRow(row);
                        break;
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Cannot Delete", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_ClassTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField nameField = new JTextField(25);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Intake Module:"));
        
        JComboBox<String> IMIDList = new JComboBox<>();
        for(IntakeModule x : InteractTxt.allIntakeModule){
            IMIDList.addItem(x.getIMID());
        }
        panel.add(IMIDList);

        while(true){
            int result = JOptionPane.showConfirmDialog(this, panel, "New Intake", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result != JOptionPane.OK_OPTION) break;

            if (result == JOptionPane.OK_OPTION) {
                String name = nameField.getText().trim();
                String IMID = (String) IMIDList.getSelectedItem();

                if (ErrorChecking.checkInput(name).equals("null")){
                    JOptionPane.showMessageDialog(this, "Name is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("number")){
                    JOptionPane.showMessageDialog(this, "Name cannot in number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("String")){
                    int max = 0;
                    for(project.roles.Class x : InteractTxt.allClass){
                        String numPart = x.getClassId().substring(1);
                        int num = Integer.parseInt(numPart);
                        if (num > max) {
                            max = num;
                        }
                    }
                    String ClassId = "C" + (max + 1);
                    InteractTxt.allClass.add(new project.roles.Class(ClassId, name, "NA", IMID));
                    InteractTxt.checkIMID(IMID).IM_Classes.add(InteractTxt.checkClassID(ClassId));
                    project.roles.Class New = InteractTxt.checkClassID(ClassId);

                    InteractTxt.saveDatabase();
                    
                    String Students = "";
                    for(int i=0; i < New.Class_Students.size(); i++){
                        if(i == (New.Class_Students.size()-1)){
                            Students += New.Class_Students.get(i).getId();
                        }else{
                            Students += New.Class_Students.get(i).getId() + ", ";
                        }
                    }

                    model.addRow(new String[]{New.getClassId(), New.getClassName(), New.getLecId(), New.getIMID(), Students});
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageClasses().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClassTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
