package project.gui.admin;

import java.awt.*;
import java.security.SecureRandom;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;

public class ManageLecturers extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel(
        new String[]{"Lecturer ID", "Name", "Email", "Assigned Leader"}, 0
    );
    
    public ManageLecturers() {
        initComponents();
        InteractTxt.readUser();
        for(Lecturer x : InteractTxt.allLecturer){
                model.addRow(new String[]{x.getId(), x.getName(), x.getEmail(), x.getLeader().getId()});
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LecturerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jButton3.setText("Save");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lecturers");

        LecturerTable.setModel(model);
        LecturerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecturerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LecturerTable);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(194, 194, 194)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField nameField = new JTextField(25);
        JTextField emailField = new JTextField(25);
        JComboBox<String> leaderList = new JComboBox<>();
        for(Leader x : InteractTxt.allLeader){
            leaderList.addItem(x.getId());
        }

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Leader:"));
        panel.add(leaderList);

        int result = JOptionPane.showConfirmDialog(this, panel, "New Lecturer", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            String name = nameField.getText();
            String email = emailField.getText();
            String leaderId = (String) leaderList.getSelectedItem();
            
            int max = 0;
            for(Lecturer x : InteractTxt.allLecturer){
                String numPart = x.getId().substring(2);
                int num = Integer.parseInt(numPart);
                if (num > max) {
                    max = num;
                }
            }
            for(Leader x : InteractTxt.allLeader){
                String numPart = x.getId().substring(2);
                int num = Integer.parseInt(numPart);
                if (num > max) {
                    max = num;
                }
            }
            String id = "lc" + (max + 1);
            
            String upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            String lower = "abcdefghijklmnopqrstuvwxyz";
            String number = "0123456789";
            String symbol = "!@#$%^&*()-_=+[]{};:,.<>?/";
            SecureRandom random = new SecureRandom();
            ArrayList<Character> pw = new ArrayList<>();
            pw.add(upper.charAt(random.nextInt(upper.length())));
            pw.add(lower.charAt(random.nextInt(lower.length())));
            pw.add(number.charAt(random.nextInt(number.length())));
            pw.add(symbol.charAt(random.nextInt(symbol.length())));
            String all = upper + lower + number + symbol;
            for (int i = 4; i < 12; i++) {
                pw.add(all.charAt(random.nextInt(all.length())));
            }
            StringBuilder builder = new StringBuilder();
            for (char c : pw) {
                builder.append(c);
            }
            String password = builder.toString();
            
            String [] userdata = {id, name, email, password, "lecturer"};
            InteractTxt.allLecturer.add(new Lecturer(userdata));
            
            InteractTxt.checkLecID(id).setLeader(InteractTxt.checkLeaID(leaderId));
            InteractTxt.checkLeaID(leaderId).leaderTeam.add(InteractTxt.checkLecID(id));
            
            InteractTxt.writeUser();
            Lecturer New = InteractTxt.checkLecID(id);
            model.addRow(new String[]{New.getId(), New.getName(), New.getEmail(), New.getLeader().getId()});
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LecturerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecturerTableMouseClicked
        int row = LecturerTable.getSelectedRow();
        Lecturer Lec = InteractTxt.allLecturer.get(row);

        JTextField nameField = new JTextField(25);
        nameField.setText(Lec.getName());
        JTextField emailField = new JTextField(25);
        emailField.setText(Lec.getEmail());
        JComboBox<String> leaderList = new JComboBox<>();
        for(Leader x : InteractTxt.allLeader){
            leaderList.addItem(x.getId());
        }
        leaderList.setSelectedItem(Lec.getLeader().getId());

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Leader:"));
        panel.add(leaderList);

        int result = JOptionPane.showConfirmDialog(this, panel, Lec.getId(), JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String name = nameField.getText();
            String email = emailField.getText();
            String leaderId = (String) leaderList.getSelectedItem();

            Lec.setName(name);
            Lec.setEmail(email);
            Lec.getLeader().leaderTeam.remove(Lec);
            Lec.setLeader(InteractTxt.checkLeaID(leaderId));
            Lec.getLeader().leaderTeam.add(Lec);

            InteractTxt.writeUser();

            model.setValueAt(name, row, 1);
            model.setValueAt(email, row, 2);
            model.setValueAt(leaderId, row, 3);
        }
    }//GEN-LAST:event_LecturerTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageLecturers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LecturerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
