package project.gui.admin;

import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;

public class ManageIntakes extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel(
        new String[]{"Intake ID", "Name", "Intake's Modules"}, 0
    );

    public ManageIntakes() {
        initComponents();
        for(Intake x : InteractTxt.allIntake){
            String Modules = "";
            for(int i=0; i < x.Int_Modules.size(); i++){
                if(i == (x.Int_Modules.size()-1)){
                    Modules += x.Int_Modules.get(i).getModuleId();
                }else{
                    Modules += x.Int_Modules.get(i).getModuleId() + ", ";
                }
            }
            model.addRow(new String[]{x.getIntakeId(), x.getIntakeName(), Modules});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IntakeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Intakes");

        IntakeTable.setModel(model);
        IntakeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntakeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(IntakeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IntakeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntakeTableMouseClicked
        int row = IntakeTable.getSelectedRow();
        Intake Int = InteractTxt.allIntake.get(row);

        JTextField nameField = new JTextField(25);
        nameField.setText(Int.getIntakeName());

        DefaultListModel<String> List = new DefaultListModel<>();
        for (project.roles.Module x : InteractTxt.allModule) {
            List.addElement(x.getModuleId());
        }
        JList<String> ModuleList = new JList<>(List);
        ModuleList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        ModuleList.setVisibleRowCount(5);
        JScrollPane moduleField = new JScrollPane(ModuleList);
        
        JPanel modulesPanel = new JPanel();
modulesPanel.setLayout(new BoxLayout(modulesPanel, BoxLayout.Y_AXIS));

ArrayList<JCheckBox> moduleBoxes = new ArrayList<>();

for (project.roles.Module x : InteractTxt.allModule) {
    JCheckBox cb = new JCheckBox(x.getModuleId());
    moduleBoxes.add(cb);
    modulesPanel.add(cb);
}

JScrollPane moduleScroll = new JScrollPane(modulesPanel);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Modules:"));
        panel.add(moduleScroll);
        
        ArrayList<String> selectedModules = new ArrayList<>();

for (JCheckBox cb : moduleBoxes) {
    if (cb.isSelected()) {
        selectedModules.add(cb.getText());
    }
}

        while(true){
            Object[] options = {"OK", "Delete", "Cancel"};
            int result = JOptionPane.showOptionDialog(this,panel,Int.getIntakeId(),JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[2]);
            if (result != 0 && result != 1) break;

            if (result == 0) {
                String name = nameField.getText().trim();
                ArrayList<String> selectedModules = new ArrayList<>(ModuleList.getSelectedValuesList());
                
                for(String x : selectedModules){
                    System.out.println(x);
                }

                if(ErrorChecking.checkInput(name).equals("null")){
                    JOptionPane.showMessageDialog(this, "Name is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("number")){
                    JOptionPane.showMessageDialog(this, "Name cannot in number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("String")){
                    Int.setIntakeName(name);

                    InteractTxt.writeIntake();

                    model.setValueAt(name, row, 1);
                    break;
                }
            }

            if (result == 1) {
//                int confirm = JOptionPane.showConfirmDialog(this, "Do you sure to delete the Leader?", "Confirm", JOptionPane.YES_NO_OPTION);
//                if (confirm == JOptionPane.OK_OPTION) {
//                    InteractTxt.allIntake.remove(Int);
//                    for (Lecturer x : Lea.leaderTeam){
//                            x.setLeader(null);
//                        }
//
//                    Lea.leaderTeam.clear();
//
//                    InteractTxt.saveDatabase();
//                    model.removeRow(row);
//                    break;
//                }
            }
        }

    }//GEN-LAST:event_IntakeTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageIntakes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable IntakeTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
