package project.gui.admin;

import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;

public class ManageAcademicLeaders extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel(
        new String[]{"Leader ID", "Name", "Email", "Lecturers Assigned"}, 0
    );
    
    public ManageAcademicLeaders() {
        initComponents();
        for(Leader x : InteractTxt.allLeader){
            String Lecturers = "";
            for(int i=0; i < x.leaderTeam.size(); i++){
                if(i == (x.leaderTeam.size()-1)){
                    Lecturers += x.leaderTeam.get(i).getId();
                }else{
                    Lecturers += x.leaderTeam.get(i).getId() + ", ";
                }
            }
            model.addRow(new String[]{x.getId(), x.getName(), x.getEmail(), Lecturers});
        }
        
        LeaderTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int row = LeaderTable.rowAtPoint(e.getPoint());
                int col = LeaderTable.columnAtPoint(e.getPoint());
                if (row > -1 && col == 3) {
                    Object value = LeaderTable.getValueAt(row, col);
                    LeaderTable.setToolTipText(value == null ? null : value.toString());
                } else {
                    LeaderTable.setToolTipText(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LeaderTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Academic Leaders");

        LeaderTable.setModel(model);
        LeaderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeaderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LeaderTable);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField nameField = new JTextField(25);
        JTextField emailField = new JTextField(25);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);

        while(true){
            int result = JOptionPane.showConfirmDialog(this, panel, "New Academic Leader", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result != JOptionPane.OK_OPTION) break;
            
            if (result == JOptionPane.OK_OPTION) {
                String name = nameField.getText().trim();
                String email = emailField.getText().trim();
                
                if(ErrorChecking.checkInput(name).equals("null")){
                    JOptionPane.showMessageDialog(this, "Name is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("number")){
                    JOptionPane.showMessageDialog(this, "Name cannot in number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkEmail(email).equals("null")){
                    JOptionPane.showMessageDialog(this, "Email is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkEmail(email).equals("not email")){
                    JOptionPane.showMessageDialog(this, "Email must be in email format", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkEmail(email).equals("same")){
                    JOptionPane.showMessageDialog(this, "Email must be Unique", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("String") && ErrorChecking.checkEmail(email).equals("String")){
                    int max = 0;
                    for(Lecturer x : InteractTxt.allLecturer){
                        String numPart = x.getId().substring(2);
                        int num = Integer.parseInt(numPart);
                        if (num > max) {
                            max = num;
                        }
                    }
                    for(Leader x : InteractTxt.allLeader){
                        String numPart = x.getId().substring(2);
                        int num = Integer.parseInt(numPart);
                        if (num > max) {
                            max = num;
                        }
                    }
                    String id = "lc" + (max + 1);

                    String password = Tools.GeneratePW();

                    String [] userdata = {id, name, email, password, "leader"};
                    InteractTxt.allLeader.add(new Leader(userdata));

                    InteractTxt.writeUser();
                    Leader New = InteractTxt.checkLeaID(id);
                    model.addRow(new String[]{New.getId(), New.getName(), New.getEmail()});
                    break;
                }
            }
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void LeaderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderTableMouseClicked
        int row = LeaderTable.getSelectedRow();
        Leader Lea = InteractTxt.allLeader.get(row);

        JTextField nameField = new JTextField(25);
        nameField.setText(Lea.getName());
        JTextField emailField = new JTextField(25);
        emailField.setText(Lea.getEmail());

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);

        while(true){
            Object[] options = {"OK", "Delete", "Cancel"};
            int result = JOptionPane.showOptionDialog(this,panel,Lea.getId(),JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[2]);
            if (result != 0 && result != 1) break;
            
            if (result == 0) {
                String name = nameField.getText().trim();
                String email = emailField.getText().trim();
                
                if(ErrorChecking.checkInput(name).equals("null")){
                    JOptionPane.showMessageDialog(this, "Name is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("number")){
                    JOptionPane.showMessageDialog(this, "Name cannot in number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkEmail(email).equals("null")){
                    JOptionPane.showMessageDialog(this, "Email is required", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkEmail(email).equals("not email")){
                    JOptionPane.showMessageDialog(this, "Email must be in email format", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkEmail(email).equals("same") && !email.equals(Lea.getEmail())){
                    JOptionPane.showMessageDialog(this, "Email must be Unique", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                } else if (ErrorChecking.checkInput(name).equals("String") && (ErrorChecking.checkEmail(email).equals("String") || email.equals(Lea.getEmail()))){
                    Lea.setName(name);
                    Lea.setEmail(email);

                    InteractTxt.writeUser();

                    model.setValueAt(name, row, 1);
                    model.setValueAt(email, row, 2);
                    break;
                }
            }
            
            if (result == 1) {
//                int confirm = JOptionPane.showConfirmDialog(this, "Do you sure to delete the Leader?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
//                if (confirm == JOptionPane.OK_OPTION) {
//                    InteractTxt.allLeader.remove(Lea);
//                    for (Lecturer x : Lea.leaderTeam){
//                        x.setLeader(null);
//                    }
//
//                    Lea.leaderTeam.clear();
//
//                    InteractTxt.saveDatabase();
//                    model.removeRow(row);
//                    break;
//                }

                if(Lea.leaderTeam.isEmpty()){
                    int confirm = JOptionPane.showConfirmDialog(this, "Do you sure to delete the Leader?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.OK_OPTION) {
                        InteractTxt.allLeader.remove(Lea);

                        InteractTxt.saveDatabase();
                        model.removeRow(row);
                        break;
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Cannot Delete", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_LeaderTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAcademicLeaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAcademicLeaders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LeaderTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
