package project.gui.admin;

import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;

public class ManageIntakes extends FrameFormat {

    private Admin sessionUser;
    private DefaultTableModel model = new DefaultTableModel(
        new String[]{"Intake ID", "Name", "Intake's Modules"}, 0
    );

    public ManageIntakes(Admin sessionUser) {
        initComponents();
        super.formatWindow("Intakes");
        this.sessionUser = sessionUser;
        for(Intake x : InteractTxt.allIntake){
            model.addRow(new String[]{x.getIntakeId(), x.getIntakeName(), x.getModulesAsString()});
        }
        
        Tools.enableTooltip(IntakeTable, Set.of(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IntakeTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Intakes");

        IntakeTable.setModel(model);
        IntakeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntakeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(IntakeTable);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        openPage(new Dashboard(sessionUser));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IntakeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntakeTableMouseClicked
        int row = IntakeTable.getSelectedRow();
        Intake Int = InteractTxt.allIntake.get(row);

        JTextField nameField = new JTextField(25);
        nameField.setText(Int.getIntakeName());
                
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Name:"));
        panel.add(Box.createVerticalStrut(8));
        panel.add(nameField);
        panel.add(Box.createVerticalStrut(16));
        panel.add(new JLabel("Modules:"));
        panel.add(Box.createVerticalStrut(8));
        
        JPanel modulesPanel = new JPanel();
        modulesPanel.setLayout(new BoxLayout(modulesPanel, BoxLayout.Y_AXIS));
        ArrayList<JCheckBox> moduleBoxes = new ArrayList<>();
        for (project.roles.Module x : InteractTxt.allModule) {
            JCheckBox cb = new JCheckBox(x.toString());
            cb.putClientProperty("module", x);

            for(project.roles.Module y : InteractTxt.checkInt_Modules(Int.getIntakeId())){
                if (x.getModuleId().equals(y.getModuleId())) {
                    cb.setSelected(true);
                }
            }
            moduleBoxes.add(cb);
            modulesPanel.add(cb);
        }
        JScrollPane moduleScroll = new JScrollPane(modulesPanel);
        panel.add(moduleScroll);
        
        nameField.setPreferredSize(new Dimension(260, 24));
        moduleScroll.setPreferredSize(new Dimension(260,100));
        
        boolean emptyStu = Int.checkEmptyStu();
        if(!emptyStu){
            for (JCheckBox cb : moduleBoxes) {
                cb.setEnabled(false);
            }
        }

        while(true){
            Object[] options = {"OK", "Delete", "Cancel"};
            int result = JOptionPane.showOptionDialog(this,panel,Int.getIntakeId(),JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[2]);
            if (result != 0 && result != 1) break;

            if (result == 0) {
                String name = nameField.getText().trim();
                ArrayList<project.roles.Module> selectedModules = new ArrayList<>();
                for (JCheckBox cb : moduleBoxes) {
                    if (cb.isSelected()) {
                        selectedModules.add((project.roles.Module) cb.getClientProperty("module"));
                    }
                }
                
                ValidationResult nameResult = ErrorChecking.checkInput(name);
                
                if (nameResult != ValidationResult.OK) {
                    showNameError(nameResult);
                }else{
                    for(project.roles.Module x : InteractTxt.checkInt_Modules(Int.getIntakeId())){
                        boolean delete = true;
                        if(selectedModules.contains(x)){
                            delete = false;
                        }
                        if(delete){
                            Int.deleteIntakeModule(x);
                        }
                    }
                    for(project.roles.Module y : selectedModules){
                        boolean add = true;
                        for(project.roles.Module x : InteractTxt.checkInt_Modules(Int.getIntakeId())){
                            if(x == y){
                                add = false;
                            }
                        }
                        if(add){
                            Int.createIntakeModule(y.getModuleId());
                        }
                    }
                    Int.setIntakeName(name);

                    InteractTxt.saveDatabase();

                    model.setValueAt(name, row, 1);
                    model.setValueAt(Int.getModulesAsString(), row, 2);
                    break;
                }
            }

            if (result == 1) {
                if(emptyStu){
                    int confirm = JOptionPane.showConfirmDialog(this, "Do you sure to delete the Intake?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.OK_OPTION) {
                        InteractTxt.allIntake.remove(Int);
                        for(project.roles.Module x : InteractTxt.checkInt_Modules(Int.getIntakeId())){
                            Int.deleteIntakeModule(x);
                        }
                        
                        InteractTxt.saveDatabase();
                        model.removeRow(row);
                        break;
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Cannot Delete", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_IntakeTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField idField = new JTextField(25);
        JTextField nameField = new JTextField(25);
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Intake ID:"));
        panel.add(Box.createVerticalStrut(8));
        panel.add(idField);
        panel.add(Box.createVerticalStrut(16));
        panel.add(new JLabel("Name:"));
        panel.add(Box.createVerticalStrut(8));
        panel.add(nameField);
        panel.add(Box.createVerticalStrut(16));
        panel.add(new JLabel("Modules:"));
        panel.add(Box.createVerticalStrut(8));
        
        JPanel modulesPanel = new JPanel();
        modulesPanel.setLayout(new BoxLayout(modulesPanel, BoxLayout.Y_AXIS));
        ArrayList<JCheckBox> moduleBoxes = new ArrayList<>();
        for (project.roles.Module x : InteractTxt.allModule) {
            JCheckBox cb = new JCheckBox(x.toString());
            cb.putClientProperty("module", x);
            moduleBoxes.add(cb);
            modulesPanel.add(cb);
        }
        JScrollPane moduleScroll = new JScrollPane(modulesPanel);
        panel.add(moduleScroll);
        
        idField.setPreferredSize(new Dimension(260, 24));
        nameField.setPreferredSize(new Dimension(260, 24));
        moduleScroll.setPreferredSize(new Dimension(260,100));

        while(true){
            int result = JOptionPane.showConfirmDialog(this, panel, "New Intake", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result != JOptionPane.OK_OPTION) break;

            if (result == JOptionPane.OK_OPTION) {
                String id = idField.getText().trim();
                String name = nameField.getText().trim();
                ArrayList<project.roles.Module> selectedModules = new ArrayList<>();
                for (JCheckBox cb : moduleBoxes) {
                    if (cb.isSelected()) {
                        selectedModules.add((project.roles.Module) cb.getClientProperty("module"));
                    }
                }
                
                ValidationResult nameResult = ErrorChecking.checkInput(name);
                ValidationResult idResult = ErrorChecking.checkID(id);
                
                if (nameResult != ValidationResult.OK) {
                    showNameError(nameResult);
                }else if (idResult != ValidationResult.OK) {
                    showIDError(idResult);
                }else{
                    InteractTxt.allIntake.add(new Intake(id, name));
                    Intake New = InteractTxt.checkIntID(id);
                    
                    for(project.roles.Module y : selectedModules){
                        New.createIntakeModule(y.getModuleId());
                    }
                    
                    InteractTxt.saveDatabase();
                    
                    model.addRow(new String[]{New.getIntakeId(), New.getIntakeName(), New.getModulesAsString()});
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String input = jTextField1.getText().trim();
        ArrayList<Intake> matched = Intake.search(input);
        model.setRowCount(0);
        if (matched.isEmpty()) {
            for(Intake x : InteractTxt.allIntake){
                model.addRow(new String[]{x.getIntakeId(), x.getIntakeName(), x.getModulesAsString()});
            }
            JOptionPane.showMessageDialog(this, input + " Doesn't Have Any Matched Result", "Unable To Found", JOptionPane.ERROR_MESSAGE);
        } else {
            for(Intake x : matched){
                model.addRow(new Object[]{x.getIntakeId(), x.getIntakeName(), x.getModulesAsString()});
            }
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageIntakes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageIntakes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable IntakeTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
