/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui.leader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.utils.*;
import project.roles.*;
import project.roles.Module;
/**
 *
 * @author US
 */
public class LeaderModule extends FrameFormat {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LeaderModule.class.getName());
    private Leader sessionUser;
//    private IntakeModule intMod;
//    private Module mod;
    private DefaultTableModel model = new DefaultTableModel();
    private int row =-1;
    private String[] columnName = {"IMID","Module ID", "Module Name","Intake ID","Intake Name"};
    /**
     * Creates new form LeaderModule
     */
//    public LeaderModule(Leader sessionUser, IntakeModule intMod, Module mod)
    public LeaderModule(Leader sessionUser) {
        initComponents();
        super.formatWindow("Leader Module");
        this.sessionUser = sessionUser;
//        this.intMod = intMod;
//        this.mod = mod;

        model.setColumnIdentifiers(columnName);
       
        loadModuleData();
  
    }
        
    public void loadModuleData() {
    model.setRowCount(0);  // Clear existing rows
    
    for (IntakeModule im : InteractTxt.allIntakeModule) {
        Module module = InteractTxt.checkModID(im.getModuleId());
        Intake intake = InteractTxt.checkIntID(im.getIntakeId());
        
        if (module != null) {
            String moduleName = module.getModuleName();
            String intakeId = im.getIntakeId();
            String intakeName = (intake != null) ? intake.getIntakeName() : "Unknown";
            String lecturers = "";
            for (Lecturer lec : module.Mod_Lecturers){
                lecturers += lec.getName() + " ";
            }
            
            // ✅ CORRECT ORDER - matches columnName array
            Object[] row = {
                im.getIMID(),            // [0] IMID
                module.getModuleId(),    // [1] Module ID
                moduleName,              // [2] Module Name
                intakeId,                // [3] Intake ID
                intakeName,              // [4] Intake Name
                lecturers
            };
            model.addRow(row);
            
            // Debug output
            System.out.println(
                im.getIMID() + ", " +
                module.getModuleId() + ", " +
                moduleName + ", " +
                intakeId + ", " +
                intakeName+ ", " +
                lecturers
            );
        }
    }
    
    System.out.println("Total assignments loaded: " + model.getRowCount());
}

    
    
//    private void loadModules() {
//        model.setRowCount(0); // Clear existing rows
//        
//        for (Module module : InteractTxt.allModule) {
//            // Count lecturers assigned to this module
//            int lecturerCount = module.Mod_Lecturers.size();
//            
//            Object[] row = {
//                module.getModuleId(),
//                module.getModuleName(),
//                lecturerCount + " lecturer(s)"
//            };
//            System.out.println(row);
//            model.addRow(row);
//        }
//        
////        statusLabel.setText("Loaded " + InteractTxt.allModule.size() + " modules");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add Module");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Module");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete Module");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("BUTTON CLICKED!"); 
        new LeaderAddModule(sessionUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("BUTTON CLICKED!"); 
        new LeaderEditModule(sessionUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new LeaderModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
