/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui.student;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import project.roles.*;
import project.utils.*;
import project.utils.FrameFormat;



public class StudentClassRegistration extends FrameFormat {
    private Student sessionStudent;
    private String intakeId;
    private DefaultTableModel tableModel;

    /**
     * Creates new form StudentClassRegistration
     */
    public StudentClassRegistration(Student student) {        
        initComponents();
        
        this.sessionStudent = student;
        this.intakeId = student.getIntakeId();
        
        setupTables();
        populateModuleTable();
        setupModuleSelectionListener();

    }
    
    private void setupTables() {
    // Module table
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] { "Module ID", "Module Name" }
    ) {
        public boolean isCellEditable(int row, int column) { return false; }
    });

    // Class table
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] { "Class ID", "Class Name" }
    ) {
        public boolean isCellEditable(int row, int column) { return false; }
    });
}
    private void populateModuleTable() {
    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
    model1.setRowCount(0); // clear table first

    Intake intake = InteractTxt.checkIntID(intakeId);
    if (intake != null) {
        for (project.roles.Module m : intake.Int_Modules) {
            model1.addRow(new Object[]{ m.getModuleId(), m.getModuleName() });
        }
    }
}
private void setupModuleSelectionListener() {
    jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                String moduleId = jTable1.getValueAt(selectedRow, 0).toString();
                populateClassTable(moduleId);
            }
        }
    });
}

private void populateClassTable(String moduleId) {
    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    model2.setRowCount(0); // clear old data

    // Loop through all IntakeModule objects
    for (IntakeModule im : InteractTxt.allIntakeModule) {
        if (im.getIntakeId().equals(intakeId) && im.getModuleId().equals(moduleId)) {
            for (project.roles.Class c : im.IM_Classes) {
                model2.addRow(new Object[]{ c.getClassId(), c.getClassName() });
            }
        }
    }
}



    /**
     * Load all modules for this student based on IntakeID
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Module", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Class"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
