/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.main;

import javax.swing.JOptionPane;
import project.utils.*;
import project.roles.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import javax.swing.JFrame;

/**
 *
 * @author US
 */
public class UserProfile extends FrameFormat {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserProfile.class.getName());
    private User sessionUser;
    private String dashboardClassName;

    public UserProfile(User sessionUser) {
        initComponents();
        this.sessionUser = sessionUser;
        super.formatWindow("User Profile");
        jLabel1.setText("User Profile");
        displayStudentFields();
        loadUserData();
    }

    private void loadUserData() {
        idField.setText(sessionUser.getId());
        nameField.setText(sessionUser.getName());
        emailField.setText(sessionUser.getEmail());
        pwField.setText(sessionUser.getPW());
        roleField.setText(sessionUser.getRole());

        if (sessionUser instanceof Student) {
            Student student = (Student) sessionUser;

            String intakeId = student.getIntakeId();
            if (intakeId != null && !intakeId.isEmpty()) {
                Intake intake = InteractTxt.checkIntID(intakeId);
                if (intake != null) {
                    intakeField.setText(intakeId + " - " + intake.getIntakeName());
                } else {
                    intakeField.setText(intakeId);
                }
            }
            String dob = student.getDob();
            dobField.setText(dob);

        }
    }

    private void displayStudentFields() {
        boolean isStudent = sessionUser instanceof Student;

        dobLabel.setVisible(isStudent);
        dobField.setVisible(isStudent);
        intakeLabel.setVisible(isStudent);
        intakeField.setVisible(isStudent);
    }

    private boolean isValidDOB(String dob) {
        if (dob == null || dob.isEmpty()) {
            return false;
        }

        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd")
            .withResolverStyle(ResolverStyle.STRICT);
            
            LocalDate parsedDate = LocalDate.parse(dob, formatter);

            // Block future dates
            if (parsedDate.isAfter(LocalDate.now())) {
                return false;
            }

            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        roleField = new javax.swing.JTextField();
        passwordDisplayControl = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pwField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        intakeLabel = new javax.swing.JLabel();
        intakeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Password");

        jLabel6.setText("Role");

        idField.setEditable(false);
        idField.setText("jTextField1");

        nameField.setText("jTextField2");

        emailField.setText("jTextField3");

        roleField.setEditable(false);
        roleField.setText("jTextField5");

        passwordDisplayControl.setText("Show Password");
        passwordDisplayControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordDisplayControlActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pwField.setText("jPasswordField1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User Profile");

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Email");

        dobLabel.setText("DOB");

        dobField.setText("jTextField1");

        intakeLabel.setText("Intake");

        intakeField.setEditable(false);
        intakeField.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addComponent(intakeLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dobLabel)
                                                .addGap(9, 9, 9)))
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intakeField)
                                    .addComponent(pwField)
                                    .addComponent(emailField)
                                    .addComponent(nameField)
                                    .addComponent(idField)
                                    .addComponent(roleField)
                                    .addComponent(dobField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passwordDisplayControl)
                                        .addGap(0, 237, Short.MAX_VALUE)))))))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordDisplayControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeLabel)
                    .addComponent(intakeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordDisplayControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordDisplayControlActionPerformed
        // TODO add your handling code here:
        if (passwordDisplayControl.isSelected()) {
            pwField.setEchoChar((char) 0);
        } else {
            pwField.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordDisplayControlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String newName = nameField.getText().trim();
        String newEmail = emailField.getText().trim().toLowerCase();
        String newPassword = new String(pwField.getPassword());

        // Validate input
        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (newEmail.isEmpty() || !newEmail.contains("@")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (newPassword.isEmpty() || newPassword.length() < 8) {
            JOptionPane.showMessageDialog(this, "Please enter a password with at least 8 characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        sessionUser.setName(newName);
        sessionUser.setEmail(newEmail);
        sessionUser.setPW(newPassword);

        if (sessionUser instanceof Student) {
            String dob = dobField.getText().trim();

            if (!isValidDOB(dob)) {
                JOptionPane.showMessageDialog(this, "Invalid Date of Birth!\nFormat: YYYY-MM-DD\nExample: 2005-02-14", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        }
        InteractTxt.saveDatabase();
        JOptionPane.showMessageDialog(this, "Profile is saved.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame dashboard = null;

        switch (sessionUser.getRole()) {
            case "leader":
                dashboard = new project.gui.leader.LeaderDashboard((Leader) sessionUser);
                break;
            case "lecturer":
                dashboard = new project.gui.lecturer.LecturerDashboard((Lecturer) sessionUser);
                break;
            case "student":
                dashboard = new project.gui.student.StudentHomepage((Student) sessionUser);
                break;
//            case "admin":
//                dashboard = new project.gui.admin.Dashboard(); // admin dashboard takes no args
//                break;
        }

        if (dashboard != null) {
            dashboard.setVisible(true); // show the dashboard
            this.dispose();             // close current page
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                test student
//                InteractTxt.initDatabase();
//              
//                String testId = "tp076267";   
//             
//                InteractTxt.allStudent.forEach(s -> {
//                    if (s.getId().equalsIgnoreCase(testId)) {
//
//                        java.awt.EventQueue.invokeLater(() -> {
//                            new UserProfile(s).setVisible(true);
//                        });
//
//                    }
//                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField intakeField;
    private javax.swing.JLabel intakeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox passwordDisplayControl;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JTextField roleField;
    // End of variables declaration//GEN-END:variables
}
