/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui.lecturer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import project.roles.*;
import project.utils.*;

/**
 *
 * @author Khoo Guo Hao
 */
public class DesignAssessment0 extends FrameFormat {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DesignAssessment0.class.getName());
    private final Lecturer sessionUser;
    private Intake chosenIntake;
    private IntakeModule chosenIM = null;
    
    /**
     * Creates new form DesignAssessment
     */
    
    private void clearTextForUser() {
        chosenIM = null;
        textForUser.setText("Choose a module~");
    }
    
    private void setTextForUser(String IMID, String details) {
        textForUser.setText("<html><div style='text-align: center;'><p>Proceed to Design Assessment page for "+IMID+":</p><p>"+details+"</p></div></html>");
    }
    
    private void disableModuleDropdown() {
        moduleDropdown.setEnabled(false);
        AutoCompleteDecorator.decorate(moduleDropdown);
    }
    
    public DesignAssessment0(Lecturer sessionUser) {
        initComponents();
        super.formatWindow("Design Module Assessment - Select Class");
        this.sessionUser = sessionUser;
        
        intakeDropdown.setEditable(true);
        intakeDropdown.addItem("None");
        intakeDropdown.setSelectedItem("None");
        
        InteractTxt.allIntake.forEach(i -> {
            String item = i.getIntakeId() + " (" + i.getIntakeName() + ")";
            intakeDropdown.addItem(item);
        });
        
        AutoCompleteDecorator.decorate(intakeDropdown);
        intakeDropdown.setMaximumRowCount(6);
        
        disableModuleDropdown();
        moduleDropdown.setMaximumRowCount(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        intakeDropdown = new javax.swing.JComboBox<>();
        moduleDropdown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editClassButt = new javax.swing.JButton();
        textForUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intakeDropdown.addActionListener(this::intakeDropdownActionPerformed);

        moduleDropdown.addActionListener(this::moduleDropdownActionPerformed);

        jLabel1.setText("Intake");

        jLabel2.setText("Module");

        editClassButt.setText("Edit");
        editClassButt.addActionListener(this::editClassButtActionPerformed);

        textForUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textForUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textForUser.setText("Choose a module");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Module Assessment Designs");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        jLabel4.setText(":");

        jLabel5.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textForUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(intakeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(moduleDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(editClassButt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addComponent(textForUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(editClassButt)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intakeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeDropdownActionPerformed
        // TODO add your handling code here:
        clearTextForUser();
        disableModuleDropdown();
        moduleDropdown.removeAllItems();
        String choice = intakeDropdown.getSelectedItem().toString();
        System.out.println(choice);

        if (choice == null || choice.isEmpty() || choice.equals("None")) 
            return;
        else {
            // valid choice
            System.out.println("------");
            String chosenIntakeId = choice.split(" \\(")[0];
            System.out.println(chosenIntakeId);
             InteractTxt.allIntake.forEach(i -> {
                String intakeId = i.getIntakeId();
                
                if (intakeId.equals(chosenIntakeId)) chosenIntake = i;
            });
            
            System.out.println("Selected i: " + chosenIntake.getIntakeName());
            System.out.println("Selected id: " + chosenIntake.getIntakeId());
            System.out.println("Modules: " + InteractTxt.checkInt_Modules(chosenIntake.getIntakeId()));
            
            //find overlap of modules from chosen intake
            //and the lecturer's (sessionUser) own modules
            ArrayList<String> ownMods = new ArrayList<String>();
            sessionUser.Lec_Modules.forEach(m -> {
                ownMods.add(m.getModuleId());
            });

            moduleDropdown.addItem("None");
            moduleDropdown.setSelectedItem("None");
            
            InteractTxt.checkInt_Modules(chosenIntake.getIntakeId()).forEach(m -> {
                String modId = m.getModuleId();
                if (ownMods.contains(modId)) moduleDropdown.addItem(modId+" ("+m.getModuleName()+")");
            });

            moduleDropdown.setEnabled(true);
        }
    }//GEN-LAST:event_intakeDropdownActionPerformed

    private void moduleDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleDropdownActionPerformed
        // TODO add your handling code here:
        clearTextForUser();
        try {
            String choice = moduleDropdown.getSelectedItem().toString();
            System.out.println(choice);

            if (choice == null || choice.isEmpty() || choice.equals("None")) 
                return;
            else {
                // valid choice
                System.out.println("------");

                String chosenModuleId = choice.split(" \\(")[0];

                System.out.println(chosenModuleId);

                InteractTxt.allIntakeModule.forEach(im -> {
                    if (chosenIntake.getIntakeId().equals(im.getIntakeId()) && chosenModuleId.equals(im.getModuleId())) {
                        chosenIM = im;
                    }
                });
                
                if (chosenIM != null) {
                    setTextForUser(chosenIM.getIMID(), chosenIM.getIntakeId()+" - "+chosenIM.getModuleId());
                }
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_moduleDropdownActionPerformed

    private void editClassButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClassButtActionPerformed
        // TODO add your handling code here:
        if (chosenIM != null) {
            new DesignAssessment1(sessionUser, chosenIM).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "You must select a module before proceeding!", "Error - Incomplete Action", 0);
        }
    }//GEN-LAST:event_editClassButtActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new LecturerDashboard(sessionUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        InteractTxt.initDatabase();
        String x = "lc076206";
        InteractTxt.allLecturer.forEach(l -> {
            System.out.println(l.getId());
            if (l.getId().equals(x)) {
                System.out.println(l.getId());
                java.awt.EventQueue.invokeLater(() -> new DesignAssessment0(l).setVisible(true));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton editClassButt;
    private javax.swing.JComboBox<String> intakeDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JComboBox<String> moduleDropdown;
    private javax.swing.JLabel textForUser;
    // End of variables declaration//GEN-END:variables
}
