/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui.lecturer;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import project.roles.*;
import project.utils.*;
/**
 *
 * @author Khoo Guo Hao
 */
public class EnterAssessmentMarks0 extends FrameFormat {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnterAssessmentMarks0.class.getName());
    private Lecturer sessionUser;
    private DefaultTableModel model = new DefaultTableModel();
    private String [] columnName = {"Student ID", "Student Name", "Class", "GPA"};
    private int row = -1;
    
    private ArrayList<String> ownMods = new ArrayList<>();
    private ArrayList<String> ownClasses = new ArrayList<>();
    private Intake chosenIntake = null;
    private IntakeModule chosenIM = null;
    private project.roles.Class chosenClass = null;
    private Student chosenStudent = null;
    
    /**
     * Creates new form EnterAssessmentMarks0
     */
    
    private void disableModuleDropdown() {
        moduleDropdown.setEnabled(false);
        AutoCompleteDecorator.decorate(moduleDropdown);
        chosenIM = null;
    }
    
    private void disableClassDropdown() {
        classDropdown.setEnabled(false);
        AutoCompleteDecorator.decorate(classDropdown);
        chosenClass = null;
    }
    
    private void disableStudentDropdown() {
        studentDropdown.setEnabled(false);
        AutoCompleteDecorator.decorate(moduleDropdown);
        chosenStudent = null;
    }
    
    public EnterAssessmentMarks0(Lecturer sessionUser) {
        model.setColumnIdentifiers(columnName);
        initComponents();
        super.formatWindow("Enter Assessment Details - Select Student");
        this.sessionUser = sessionUser;
        mainTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        mainTable.setAutoCreateRowSorter(true);
        
        sessionUser.Lec_Modules.forEach(m -> {
            ownMods.add(m.getModuleId());
        });
        
        sessionUser.Lec_Classes.forEach(c->{
            ownClasses.add(c.getClassId());
        });
        
        intakeDropdown.setEditable(true);
        InteractTxt.allIntake.forEach(i -> {
            String item = i.getIntakeId() + " (" + i.getIntakeName() + ")";
            intakeDropdown.addItem(item);
        });
        
        intakeDropdown.addItem("None");
        intakeDropdown.setSelectedItem("None");
        
        AutoCompleteDecorator.decorate(intakeDropdown);
        intakeDropdown.setMaximumRowCount(6);
        
        disableModuleDropdown();
        moduleDropdown.setMaximumRowCount(6);
        
        disableClassDropdown();
        classDropdown.setMaximumRowCount(6);
        
        disableStudentDropdown();
        studentDropdown.setMaximumRowCount(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        intakeDropdown = new javax.swing.JComboBox<>();
        moduleDropdown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchStudentsButt = new javax.swing.JButton();
        textForUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        classDropdown = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        studentDropdown = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intakeDropdown.addActionListener(this::intakeDropdownActionPerformed);

        moduleDropdown.addActionListener(this::moduleDropdownActionPerformed);

        jLabel1.setText("Intake*");

        jLabel2.setText("Module*");

        searchStudentsButt.setText("Search");
        searchStudentsButt.addActionListener(this::searchStudentsButtActionPerformed);

        textForUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textForUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textForUser.setText("Filter Search");

        jLabel3.setText("Class");

        classDropdown.addActionListener(this::classDropdownActionPerformed);

        jLabel4.setText("Student");

        studentDropdown.addActionListener(this::studentDropdownActionPerformed);

        mainTable.setModel(model);
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainTableMouseReleased(evt);
            }
        });
        mainTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mainTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(mainTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(intakeDropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, 215, Short.MAX_VALUE)
                    .addComponent(classDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moduleDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentDropdown, 0, 247, Short.MAX_VALUE))
                .addGap(58, 58, 58))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(searchStudentsButt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(textForUser, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(textForUser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(moduleDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(studentDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchStudentsButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intakeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeDropdownActionPerformed
        // TODO add your handling code here:
        disableModuleDropdown();
        moduleDropdown.removeAllItems();
        String choice = intakeDropdown.getSelectedItem().toString();
        System.out.println(choice);

        if (choice == null || choice.isEmpty() || choice.equals("None")) chosenIntake = null;
        else {
            // valid choice
            System.out.println("------");
            String chosenIntakeId = choice.split(" \\(")[0];
            System.out.println(chosenIntakeId);
            chosenIntake = null;
            InteractTxt.allIntake.forEach(i -> {
                String intakeId = i.getIntakeId();

                if (intakeId.equals(chosenIntakeId)) chosenIntake = i;
            });

            System.out.println("Selected i: " + chosenIntake.getIntakeName());
            System.out.println("Selected id: " + chosenIntake.getIntakeId());
            System.out.println("Modules: " + chosenIntake.Int_Modules);

            //find overlap of modules from chosen intake
            //and the lecturer's (sessionUser) own modules

            chosenIntake.Int_Modules.forEach(m -> {
                String modId = m.getModuleId();
                if (ownMods.contains(modId)) moduleDropdown.addItem(modId+" ("+m.getModuleName()+")");
            });

            moduleDropdown.addItem("None");
            moduleDropdown.setSelectedItem("None");
            moduleDropdown.setEnabled(true);
        }
    }//GEN-LAST:event_intakeDropdownActionPerformed

    private void moduleDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleDropdownActionPerformed
        // TODO add your handling code here:
        disableClassDropdown();
        classDropdown.removeAllItems();
        try {
            String choice = moduleDropdown.getSelectedItem().toString();
            System.out.println(choice);

            if (choice == null || choice.isEmpty() || choice.equals("None")) chosenIM = null;
            else {
                // valid choice
                System.out.println("------");

                String chosenModuleId = choice.split(" \\(")[0];

                System.out.println(chosenModuleId);
                
                InteractTxt.allIntakeModule.forEach(im -> {
                    if (chosenIntake.getIntakeId().equals(im.getIntakeId()) && chosenModuleId.equals(im.getModuleId())) {
                        chosenIM = im;
                    }
                });

                if (chosenIM != null) {
                    JOptionPane.showMessageDialog(this, "Assessment edit failed.\nReport this error.", "Error - Unknown Error", 0);
                } else {
                    
                    chosenIM.IM_Classes.forEach(c -> {
                        String classId = c.getClassId();
                        if (ownClasses.contains(classId)) classDropdown.addItem(classId+" ("+c.getClassName()+")");
                    });
                    
                    classDropdown.addItem("None");
                    classDropdown.setSelectedItem("None");
                    classDropdown.setEnabled(true);
                    
                }
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_moduleDropdownActionPerformed

    private void searchStudentsButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentsButtActionPerformed
        // TODO add your handling code here:
        
        if (chosenIntake == null || chosenIM == null) {
            JOptionPane.showMessageDialog(this, "Intake and Module must be chosen to proceed.\nIf you did, kindly report this error.", "Error - Incomplete Action", 0);
        } else {
            //chosenIM must be present
            
            String showIntakeId = chosenIntake.getIntakeId();
            String showModuleId = chosenIM.getModuleId();
                    
            if (chosenClass == null && chosenStudent != null) JOptionPane.showMessageDialog(this, "Student selection failed.\nReport this error.", "Error - Unknown Error", 0);
            else if (chosenClass == null && chosenStudent == null) {
                // only choose intake module - show everyone in the intake module who is under the session user
                chosenIM.IM_Classes.forEach(c -> {
                    String tableClassId = c.getClassId();
                    c.Class_Students.forEach(s -> {
//                        String s.getId();
//                        s.getName();
                    });
                });
            } else if (chosenClass != null && chosenStudent == null) {
                // choose intake & class - show everyone in that class (already guaranteed under session user)

            } else if (chosenClass != null && chosenStudent != null) {
                //class & student chosen - show only the student (already guaranteed under session user)
            }
        }
    }//GEN-LAST:event_searchStudentsButtActionPerformed

    private void classDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classDropdownActionPerformed
        // TODO add your handling code here:
        disableStudentDropdown();
        studentDropdown.removeAllItems();
        try {
            String choice = classDropdown.getSelectedItem().toString();
            System.out.println(choice);

            if (choice == null || choice.isEmpty() || choice.equals("None")) chosenClass = null;
            else {
                // valid choice
                System.out.println("------");

                String chosenClassId = choice.split(" \\(")[0];

                System.out.println(chosenClassId);
                
                InteractTxt.allClass.forEach(c -> {
                    if (chosenClassId.equals(c.getClassId())) {
                        chosenClass = c;
                    }
                });
                
                if (chosenClass != null) {
                    JOptionPane.showMessageDialog(this, "Assessment edit failed.\nReport this error.", "Error - Unknown Error", 0);
                } else {
                    
                    chosenClass.Class_Students.forEach(s -> {
                        classDropdown.addItem(s.getId()+" ("+s.getName()+")");
                    });
                    
                    studentDropdown.addItem("None");
                    studentDropdown.setSelectedItem("None");
                    studentDropdown.setEnabled(true);
                    
                }
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_classDropdownActionPerformed

    private void studentDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDropdownActionPerformed
        // TODO add your handling code here:
        try {
            String choice = studentDropdown.getSelectedItem().toString();
            System.out.println(choice);

            if (choice == null || choice.isEmpty() || choice.equals("None")) chosenStudent = null;
            else {
                // valid choice
                System.out.println("------");

                String chosenStuId = choice.split(" \\(")[0];

                System.out.println(chosenStuId);
                
                InteractTxt.allStudent.forEach(s -> {
                    if (chosenStuId.equals(s.getId())) {
                        chosenStudent = s;
                    }
                });
                
                if (chosenStudent != null) {
                    JOptionPane.showMessageDialog(this, "Assessment edit failed.\nReport this error.", "Error - Unknown Error", 0);
                } 
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_studentDropdownActionPerformed

    private void mainTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTableKeyReleased
        // TODO add your handling code here:
        System.out.println("In progress!");
    }//GEN-LAST:event_mainTableKeyReleased

    private void mainTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseReleased
        // TODO add your handling code here:
        row = mainTable.getSelectedRow();
        System.out.println(row);
        String stuId = String.valueOf(model.getValueAt(row, 0));
        String stuName = String.valueOf(model.getValueAt(row, 1));
        String classId = String.valueOf(model.getValueAt(row, 2));
        String gpa = String.valueOf(model.getValueAt(row, 3));

        System.out.println(stuId+" "+stuName+" "+classId+" "+gpa);
    }//GEN-LAST:event_mainTableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        InteractTxt.initDatabase();
        String x = "lc076206";
        InteractTxt.allLecturer.forEach(l -> {
            System.out.println(l.getId());
            if (l.getId().equals(x)) {
                System.out.println(l.getId());
                java.awt.EventQueue.invokeLater(() -> new EnterAssessmentMarks0(l).setVisible(true));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classDropdown;
    private javax.swing.JComboBox<String> intakeDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable mainTable;
    private javax.swing.JComboBox<String> moduleDropdown;
    private javax.swing.JButton searchStudentsButt;
    private javax.swing.JComboBox<String> studentDropdown;
    private javax.swing.JLabel textForUser;
    // End of variables declaration//GEN-END:variables
}
