/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui.lecturer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import project.roles.Intake;
import project.roles.IntakeModule;
import project.roles.Lecturer;
import project.roles.Student;
import project.utils.*;

/**
 *
 * @author Khoo Guo Hao
 */
public class ViewStudentComments extends FrameFormat {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewStudentComments.class.getName());
    private final Lecturer sessionUser;
    private final DefaultTableModel model = new DefaultTableModel();
    private final String [] columnName = {"Student ID", "Student Name", "Class", "Comment"};
    private int row = -1, totalStuInTable = 0;
    
    private ArrayList<String> ownMods = new ArrayList<>();
    private ArrayList<String> ownClasses = new ArrayList<>();
    private Intake chosenIntake = null;
    private IntakeModule chosenIM = null;
    private project.roles.Class chosenClass = null;
    private Student chosenStudent = null;
    private String intakeFullName;
    private String moduleFullName;
    /**
     * Creates new form ViewStudentComments
     */
    public ViewStudentComments(Lecturer sessionUser) {
        model.setColumnIdentifiers(columnName);
        initComponents();
        super.formatWindow("Enter Assessment Details - Select Student");
        this.sessionUser = sessionUser;
        
        mainTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        mainTable.setAutoCreateRowSorter(true);
        mainTable.setDefaultEditor(Object.class, null);
        
        sessionUser.Lec_Modules.forEach(m -> {
            ownMods.add(m.getModuleId());
        });
        
        sessionUser.Lec_Classes.forEach(c->{
            ownClasses.add(c.getClassId());
        });
        
        InteractTxt.allIntake.forEach(i -> {
            String item = i.getIntakeId() + " (" + i.getIntakeName() + ")";
            intakeDropdown.addItem(item);
        });
        
        intakeDropdown.setEditable(true);
        intakeDropdown.addItem("None");
        intakeDropdown.setSelectedItem("None");
        AutoCompleteDecorator.decorate(intakeDropdown);
        intakeDropdown.setMaximumRowCount(6);
        
        moduleDropdown.setMaximumRowCount(6);
        disableModuleDropdown();
        
        classDropdown.setMaximumRowCount(6);
        disableClassDropdown();
        
        studentDropdown.setMaximumRowCount(6);
        disableStudentDropdown();
    }
    
    // load all students in a class
    private void loadTable(ArrayList<Student> studentArray, project.roles.Class c) {
        for (Student s : studentArray) {
            String comment = s.getSpecificComment(c);
            String [] record = {s.getId(), s.getName(), c.getClassId(), comment};
            model.addRow(record);
            totalStuInTable++;
        }
        
        studentCountLabel.setText("Row Count: "+String.valueOf(totalStuInTable));
        totalStuInTable = 0;
    }
    
    // load specific student in table
    private void loadTable(project.roles.Class c, Student s) {
        String comment = s.getSpecificComment(c);
        String [] record = {s.getId(), s.getName(), c.getClassId(), comment};
        model.addRow(record);
        totalStuInTable++;
        
        studentCountLabel.setText("Row Count: "+String.valueOf(totalStuInTable));
        totalStuInTable = 0;
    }
    
    private void disableModuleDropdown() {
        moduleDropdown.setEnabled(false);
        moduleDropdown.setEditable(true);
        AutoCompleteDecorator.decorate(moduleDropdown);
        chosenIM = null;
    }
    
    private void disableClassDropdown() {
        classDropdown.setEnabled(false);
        classDropdown.setEditable(true);
        AutoCompleteDecorator.decorate(classDropdown);
        chosenClass = null;
    }
    
    private void disableStudentDropdown() {
        studentDropdown.setEnabled(false);
        studentDropdown.setEditable(true);
        AutoCompleteDecorator.decorate(studentDropdown);
        chosenStudent = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentCountLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchStudentsButt = new javax.swing.JButton();
        intakeLabel = new javax.swing.JLabel();
        textForUser = new javax.swing.JLabel();
        moduleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        classDropdown = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        studentDropdown = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        intakeDropdown = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        moduleDropdown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Intake*");

        studentCountLabel.setText("Total Count: ");

        jLabel2.setText("Module*");
        jLabel2.setMaximumSize(new java.awt.Dimension(38, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(38, 16));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Click Student Row to Insert/Edit Assessment Marks");

        searchStudentsButt.setText("Search");
        searchStudentsButt.addActionListener(this::searchStudentsButtActionPerformed);

        intakeLabel.setText("Intake: ");

        textForUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textForUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textForUser.setText("Filter Search");

        moduleLabel.setText("Module:");

        jLabel3.setText("Class");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter Student Assessment Marks");

        classDropdown.addActionListener(this::classDropdownActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        jLabel4.setText("Student");

        studentDropdown.addActionListener(this::studentDropdownActionPerformed);

        intakeDropdown.addActionListener(this::intakeDropdownActionPerformed);

        mainTable.setModel(model);
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainTableMouseReleased(evt);
            }
        });
        mainTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mainTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(mainTable);

        moduleDropdown.addActionListener(this::moduleDropdownActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(intakeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(moduleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textForUser, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(intakeDropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, 215, Short.MAX_VALUE)
                                    .addComponent(classDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moduleDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(studentDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(searchStudentsButt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textForUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(moduleDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(studentDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchStudentsButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeLabel)
                    .addComponent(moduleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentCountLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchStudentsButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentsButtActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        if (chosenIntake == null || chosenIM == null) {
            JOptionPane.showMessageDialog(this, "Intake and Module must be chosen to proceed.\nIf you did, kindly report this error.", "Error - Incomplete Action", 0);
        } else {
            //chosenIM must be present
            int total = 0;

            if (chosenClass == null && chosenStudent != null) JOptionPane.showMessageDialog(this, "Student selection failed.\nReport this error.", "Error - Unknown Error", 0);
            else if (chosenClass == null && chosenStudent == null) {
                // only choose intake module - show everyone in the intake module who is under the session user

                for (project.roles.Class c : chosenIM.IM_Classes) {
                    String tableClassId = c.getClassId();
                    if (ownClasses.contains(tableClassId)) {
                        loadTable(c.Class_Students, c);
                    }
                }
            } else if (chosenClass != null && chosenStudent == null) {
                // choose intake & class - show everyone in that class (already guaranteed under session user)
                loadTable(chosenClass.Class_Students, chosenClass);
            } else if (chosenClass != null && chosenStudent != null) {
                //class & student chosen - show only the student (already guaranteed under session user)
                loadTable(chosenClass, chosenStudent);
            }

            intakeLabel.setText("Intake: "+intakeFullName);
            moduleLabel.setText("Module: "+moduleFullName);
        }
    }//GEN-LAST:event_searchStudentsButtActionPerformed

    private void classDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classDropdownActionPerformed
        // TODO add your handling code here:
        disableStudentDropdown();
        studentDropdown.removeAllItems();
        try {
            String choice = classDropdown.getSelectedItem().toString();
            System.out.println(choice);

            if (!InteractTxt.allClass.contains(InteractTxt.checkClassID(choice.split(" ")[0])) ||choice == null || choice.isEmpty() || choice.equals("None")) chosenClass = null;
            else {
                // valid choice
                System.out.println("------");

                String chosenClassId = choice.split(" \\(")[0];

                System.out.println(chosenClassId);

                InteractTxt.allClass.forEach(c -> {
                    if (chosenClassId.equals(c.getClassId())) {
                        chosenClass = c;
                    }
                });

                if (chosenClass == null) {
                    JOptionPane.showMessageDialog(this, "Filter selection failed.\nReport this error.", "Error - Unknown Error", 0);
                } else {

                    studentDropdown.addItem("None");
                    studentDropdown.setSelectedItem("None");

                    chosenClass.Class_Students.forEach(s -> {
                        studentDropdown.addItem(s.getId()+" ("+s.getName()+")");
                    });

                    studentDropdown.setEnabled(true);

                }
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_classDropdownActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new LecturerDashboard(sessionUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void studentDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDropdownActionPerformed
        // TODO add your handling code here:
        try {
            String choice = studentDropdown.getSelectedItem().toString();
            System.out.println(choice);

            if (!InteractTxt.allStudent.contains(InteractTxt.checkStuID(choice.split(" ")[0])) || choice == null || choice.isEmpty() || choice.equals("None")) chosenStudent = null;
            else {
                // valid choice
                System.out.println("------");

                String chosenStuId = choice.split(" \\(")[0];

                System.out.println(chosenStuId);

                InteractTxt.allStudent.forEach(s -> {
                    if (chosenStuId.equals(s.getId())) {
                        chosenStudent = s;
                    }
                });

                if (chosenStudent == null) {
                    JOptionPane.showMessageDialog(this, "Filter selection failed.\nReport this error.", "Error - Unknown Error", 0);
                }
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_studentDropdownActionPerformed

    private void intakeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeDropdownActionPerformed
        // TODO add your handling code here:
        disableModuleDropdown();
        moduleDropdown.removeAllItems();
        String choice = intakeDropdown.getSelectedItem().toString();
        System.out.println(choice);

        if (!InteractTxt.allIntake.contains(InteractTxt.checkIntID(choice.split(" ")[0])) || choice == null || choice.isEmpty() || choice.equals("None")) chosenIntake = null;
        else {
            // valid choice
            System.out.println("------");
            String chosenIntakeId = choice.split(" \\(")[0];
            System.out.println(chosenIntakeId);
            chosenIntake = null;
            InteractTxt.allIntake.forEach(i -> {
                String intakeId = i.getIntakeId();

                if (intakeId.equals(chosenIntakeId)) {
                    intakeFullName = chosenIntakeId+" ("+i.getIntakeName()+")";
                    chosenIntake = i;
                }
            });

            System.out.println("Selected i: " + chosenIntake.getIntakeName());
            System.out.println("Selected id: " + chosenIntake.getIntakeId());
            System.out.println("Modules: " + InteractTxt.checkInt_Modules(chosenIntake.getIntakeId()));

            //find overlap of modules from chosen intake
            //and the lecturer's (sessionUser) own modules

            moduleDropdown.addItem("None");
            moduleDropdown.setSelectedItem("None");

            InteractTxt.checkInt_Modules(chosenIntake.getIntakeId()).forEach(m -> {
                String modId = m.getModuleId();
                if (ownMods.contains(modId)) moduleDropdown.addItem(modId+" ("+m.getModuleName()+")");
            });

            moduleDropdown.setEnabled(true);
        }
    }//GEN-LAST:event_intakeDropdownActionPerformed

    private void mainTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseReleased
        // TODO add your handling code here:
        int row = mainTable.getSelectedRow();
        String stuId = String.valueOf(model.getValueAt(row, 0));
        String stuName = String.valueOf(model.getValueAt(row, 1));
        String classId = String.valueOf(model.getValueAt(row, 2));
        String comment = String.valueOf(model.getValueAt(row, 3));

        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(6, 8, 6, 8);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        Font labelFont = new Font("Segoe UI", Font.BOLD, 12);
        Color labelColor = new Color(70, 70, 70);

        // label settings
        gbc.gridx = 0;
        gbc.weightx = 0;
        gbc.anchor = GridBagConstraints.EAST;

        // value settings
        GridBagConstraints valueGbc = new GridBagConstraints();
        valueGbc.gridx = 1;
        valueGbc.weightx = 1.0;
        valueGbc.fill = GridBagConstraints.HORIZONTAL;
        valueGbc.insets = new Insets(6, 8, 6, 8);
        valueGbc.anchor = GridBagConstraints.WEST;

        // stuId
        gbc.gridy = 0;
        JLabel label1 = new JLabel("Student ID:");
        label1.setFont(labelFont);
        label1.setForeground(labelColor);
        panel.add(label1, gbc);

        valueGbc.gridy = 0;
        panel.add(new JLabel(stuId), valueGbc);

        // stuName
        gbc.gridy = 1;
        JLabel label2 = new JLabel("Student Name:");
        label2.setFont(labelFont);
        label2.setForeground(labelColor);
        panel.add(label2, gbc);

        valueGbc.gridy = 1;
        panel.add(new JLabel(stuName), valueGbc);

        // classId
        gbc.gridy = 2;
        JLabel label3 = new JLabel("Class:");
        label3.setFont(labelFont);
        label3.setForeground(labelColor);
        panel.add(label3, gbc);

        valueGbc.gridy = 2;
        panel.add(
            new JLabel(classId + " (" + InteractTxt.checkClassID(classId).getClassName() + ")"),
            valueGbc
        );

        // comment
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.NORTHEAST;
        JLabel label4 = new JLabel("Comment:");
        label4.setFont(labelFont);
        label4.setForeground(labelColor);
        panel.add(label4, gbc);

        JTextArea commentField = new JTextArea(8, 30);
        commentField.setLineWrap(true);
        commentField.setWrapStyleWord(true);
        commentField.setText(comment);

        JScrollPane commentScroll = new JScrollPane(
                commentField,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER
        );

        valueGbc.gridy = 3;
        valueGbc.weighty = 1.0;
        valueGbc.fill = GridBagConstraints.BOTH;
        panel.add(commentScroll, valueGbc);

        // wrap panel to prevent huge dialog
        JScrollPane container = new JScrollPane(panel);
        container.setPreferredSize(new Dimension(520, 320));

        int userInput = JOptionPane.showConfirmDialog(
                this,
                container,
                "Student Comment",
                JOptionPane.OK_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_mainTableMouseReleased

    private void mainTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTableKeyReleased

    private void moduleDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleDropdownActionPerformed
        // TODO add your handling code here:
        disableClassDropdown();
        classDropdown.removeAllItems();
        try {
            String choice = moduleDropdown.getSelectedItem().toString();
            System.out.println("hello: "+choice);
            System.out.println(choice);

            if (!InteractTxt.allModule.contains(InteractTxt.checkModID(choice.split(" ")[0])) || choice == null || choice.isEmpty() || choice.equals("None")) chosenIM = null;
            else {
                // valid choice
                System.out.println("------");

                String chosenModuleId = choice.split(" \\(")[0];

                System.out.println(chosenModuleId);

                InteractTxt.allIntakeModule.forEach(im -> {
                    if (chosenIntake.getIntakeId().equals(im.getIntakeId()) && chosenModuleId.equals(im.getModuleId())) {
                        moduleFullName = chosenModuleId+" ("+InteractTxt.checkModID(chosenModuleId).getModuleName()+")";
                        chosenIM = im;
                    }
                });

                if (chosenIM == null) {
                    JOptionPane.showMessageDialog(this, "Filter selection failed.\nReport this error.", "Error - Unknown Error", 0);
                } else {

                    classDropdown.addItem("None");
                    classDropdown.setSelectedItem("None");

                    chosenIM.IM_Classes.forEach(c -> {
                        String classId = c.getClassId();
                        if (ownClasses.contains(classId)) classDropdown.addItem(classId+" ("+c.getClassName()+")");
                    });

                    classDropdown.setEnabled(true);

                }
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Error recorded: dropdown referenced without user action. Safe to ignore.");
        }
    }//GEN-LAST:event_moduleDropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            /* Create and display the form */
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            System.out.println(info.getName() + " -> " + info.getClassName());
        }

        } catch (ClassNotFoundException ex) {
            System.getLogger(ViewStudentComments.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (InstantiationException ex) {
            System.getLogger(ViewStudentComments.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IllegalAccessException ex) {
            System.getLogger(ViewStudentComments.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(ViewStudentComments.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        InteractTxt.initDatabase();
        String x = "lc076206";
        InteractTxt.allLecturer.forEach(l -> {
            System.out.println(l.getId());
            if (l.getId().equals(x)) {
                System.out.println(l.getId());
                java.awt.EventQueue.invokeLater(() -> new ViewStudentComments(l).setVisible(true));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> classDropdown;
    private javax.swing.JComboBox<String> intakeDropdown;
    private javax.swing.JLabel intakeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable mainTable;
    private javax.swing.JComboBox<String> moduleDropdown;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JButton searchStudentsButt;
    private javax.swing.JLabel studentCountLabel;
    private javax.swing.JComboBox<String> studentDropdown;
    private javax.swing.JLabel textForUser;
    // End of variables declaration//GEN-END:variables
}
